import json

with open("./env.json", 'r', encoding='utf-8') as file:
    envs = json.load(file)

RUNPOD_API = envs.get('RUNPOD_API', '')

POD_EASYCONTROL_TEMPLATE_ID = envs.get('POD_EASYCONTROL_TEMPLATE_ID', '')
POD_EASYCONTROL_STORAGE_ID = envs.get('POD_EASYCONTROL_STORAGE_ID', '')
POD_RETRY_DELAY = envs.get('POD_RETRY_DELAY', 500)
POD_CREATE_RETRY_MAX = envs.get('POD_START_RETRY_MAX', 30)
POD_START_RETRY_MAX = envs.get('POD_START_RETRY_MAX', 1200)
POD_RUN_SERVER_RETRY_MAX = envs.get('POD_PROCESS_RETRY_MAX', 720)
POD_REQUEST_TIMEOUT_RETRY_MAX = envs.get('POD_REQUEST_TIMEOUT_RETRY_MAX', 30)
POD_BASE_REQUEST_TIMEOUT = envs.get('POD_BASE_REQUEST_TIMEOUT', 5)
POD_IDLE_TIMEOUT = envs.get('POD_IDLE_TIMEOUT', 10)
POD_MAX_NUM = envs.get('POD_MAX_NUM', 3)
POD_EASYCONTROL_IMAGE_NAME = envs.get('POD_EASYCONTROL_IMAGE_NAME', 'monate615/comfyui-repo:easycontrol-pod-v1.0.5')
POD_SCALING_SENSIVITY = envs.get('POD_SCALING_SENSIVITY', 30)
POD_MIN_NUM = envs.get('POD_MIN_NUM', 1)

SERVERLESS_EASYCONTROL_ENDPOINT_ID = envs.get('SERVERLESS_EASYCONTROL_ENDPOINT_ID', '')
SERVERLESS_MAGICVIDEO_ENDPOINT_ID = envs.get('SERVERLESS_MAGICVIDEO_ENDPOINT_ID', '')

ORIGIN_IMAGE_URL = envs.get('ORIGIN_IMAGE_URL', '')