import os

RUNPOD_API = os.getenv('RUNPOD_API', None)

POD_EASYCONTROL_TEMPLATE_ID = os.getenv('POD_EASYCONTROL_TEMPLATE_ID', None)
POD_EASYCONTROL_STORAGE_ID = os.getenv('POD_EASYCONTROL_STORAGE_ID', None)
POD_RETRY_DELAY = int(os.getenv('POD_RETRY_DELAY', 500))
POD_CREATE_RETRY_MAX = int(os.getenv('POD_START_RETRY_MAX', 30))
POD_START_RETRY_MAX = int(os.getenv('POD_START_RETRY_MAX', 1200))
POD_RUN_SERVER_RETRY_MAX = int(os.getenv('POD_PROCESS_RETRY_MAX', 720))
POD_REQUEST_TIMEOUT_RETRY_MAX = int(os.getenv('POD_REQUEST_TIMEOUT_RETRY_MAX', 30))
POD_BASE_REQUEST_TIMEOUT = int(os.getenv('POD_BASE_REQUEST_TIMEOUT', 5))
POD_IDLE_TIMEOUT = int(os.getenv('POD_IDLE_TIMEOUT', 10))
POD_MAX_NUM = int(os.getenv('POD_MAX_NUM', 20))

SERVERLESS_EASYCONTROL_ENDPOINT_ID = os.getenv('SERVERLESS_EASYCONTROL_ENDPOINT_ID', None)
SERVERLESS_MAGICVIDEO_ENDPOINT_ID = os.getenv('SERVERLESS_MAGICVIDEO_ENDPOINT_ID', None)

ORIGIN_IMAGE_URL = os.getenv('ORIGIN_IMAGE_URL', None)